---
- name: configure sshd_config | {{ ansible_distribution }} {{ ansible_distribution_major_version }}
  template:
    src: sshd_config_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.j2
    dest: /etc/ssh/sshd_config
  notify:
    - reload ssh

- name: check syntax of sshd_config file
  shell: sshd -t
  register: result
  changed_when: "result.rc != 0"
  failed_when: ('ERROR' in result.stdout)
...
